default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: elo_dev

test:
  <<: *default
  database: elo_test

production:
  <<: *default
  database: elo_production
